In [4]:
import pandas as pd

df = pd.read_csv('222.csv')

df.head()

,娛樂稅稅源,申報家(件)數,查定家(件)數,申報營業總額,查定營業總額,本月份申報報繳稅額,本月份查定報繳稅額,申報報繳稅額累計數,查定報繳稅額累計數,本月份申報實徵稅額,本月份查定實徵稅額,申報實徵稅額累計數,查定實徵稅額累計數,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,合 計,457,NaN,"46,702,458",NaN,"1,739,151",NaN,"17,317,165",NaN,"1,615,980",NaN,"17,245,768",NaN,NaN,NaN,NaN,NaN,NaN
1,自動申報-總計,35,NaN,"29,135,403",NaN,"839,269",NaN,"8,081,079",NaN,"796,898",NaN,"8,036,064",NaN,NaN,NaN,NaN,NaN,NaN
2,查定課徵-總計,418,NaN,"17,170,605",NaN,"897,912",NaN,"9,095,556",NaN,"817,147",NaN,"9,067,581",NaN,NaN,NaN,NaN,NaN,NaN
3,臨時公演-總計,4,NaN,"396,450",NaN,"1,970",NaN,"140,530",NaN,"1,935",NaN,"142,123",NaN,NaN,NaN,NaN,NaN,NaN
4,違章補徵稅款-總計,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
len(df)

47

In [6]:
df

,娛樂稅稅源,申報家(件)數,查定家(件)數,申報營業總額,查定營業總額,本月份申報報繳稅額,本月份查定報繳稅額,申報報繳稅額累計數,查定報繳稅額累計數,本月份申報實徵稅額,本月份查定實徵稅額,申報實徵稅額累計數,查定實徵稅額累計數,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,合 計,457,NaN,"46,702,458",NaN,"1,739,151",NaN,"17,317,165",NaN,"1,615,980",NaN,"17,245,768",NaN,NaN,NaN,NaN,NaN,NaN
1,自動申報-總計,35,NaN,"29,135,403",NaN,"839,269",NaN,"8,081,079",NaN,"796,898",NaN,"8,036,064",NaN,NaN,NaN,NaN,NaN,NaN
2,查定課徵-總計,418,NaN,"17,170,605",NaN,"897,912",NaN,"9,095,556",NaN,"817,147",NaN,"9,067,581",NaN,NaN,NaN,NaN,NaN,NaN
3,臨時公演-總計,4,NaN,"396,450",NaN,"1,970",NaN,"140,530",NaN,"1,935",NaN,"142,123",NaN,NaN,NaN,NaN,NaN,NaN
4,違章補徵稅款-總計,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,電影0-小 計,2,-,"2,451,841",-,"10,176",-,"183,707",-,"10,142",-,"183,673",-,NaN,NaN,NaN,NaN,NaN
6,電影0-本國片繁榮地區A,-,-,-,-,-,-,-,-,-,-,-,-,NaN,NaN,NaN,NaN,NaN
7,電影0-本國片偏僻地區B,-,-,-,-,-,-,-,-,-,-,-,-,NaN,NaN,NaN,NaN,NaN
8,電影0-本國片郊區C,-,-,-,-,-,-,-,-,-,-,-,-,NaN,NaN,NaN,NaN,NaN
9,電影0-外國片繁榮地區D,-,-,-,-,-,-,-,-,-,-,-,-,NaN,NaN,NaN,NaN,NaN
10,電影0-外國片偏僻地區E,-,-,-,-,-,-,-,-,-,-,-,-,NaN,NaN,NaN,NaN,NaN
11,電影0-外國片郊區F,-,-,-,-,-,-,-,-,-,-,-,-,NaN,NaN,NaN,NaN,NaN
12,電影0-國洋片混片G,2,-,"2,451,841",-,"10,176",-,"183,707",-,"10,142",-,"183,673",-,NaN,NaN,NaN,NaN,NaN
13,電影0-其他H,-,-,-,-,-,-,-,-,-,-,-,-,NaN,NaN,NaN,NaN,NaN
14,歌廳1,-,-,-,-,-,-,-,-,-,-,-,-,NaN,NaN,NaN,NaN,NaN
15,撞球場2,-,-,-,-,-,-,-,-,-,-,-,-,NaN,NaN,NaN,NaN,NaN
16,保齡球館3,-,-,-,-,-,-,-,-,-,-,-,-,NaN,NaN,NaN,NaN,NaN
17,高爾夫球場4-小 計,1,-,"3,845,590",-,"174,800",-,"1,828,012",-,"174,800",-,"1,828,012",-,NaN,NaN,NaN,NaN,NaN
18,高爾夫球場4-球 場A,1,-,"3,845,590",-,"174,800",-,"1,828,012",-,"174,800",-,"1,828,012",-,NaN,NaN,NaN,NaN,NaN
19,高爾夫球場4-練習場B,-,-,-,-,-,-,-,-,-,-,-,-,NaN,NaN,NaN,NaN,NaN
20,舞?舞場 5-小 計,-,-,-,-,-,-,-,-,-,-,-,-,NaN,NaN,NaN,NaN,NaN
21,舞?舞場 5-舞 廳A,-,-,-,-,-,-,-,-,-,-,-,-,NaN,NaN,NaN,NaN,NaN
22,舞?舞場 5-舞 場B,-,-,-,-,-,-,-,-,-,-,-,-,NaN,NaN,NaN,NaN,NaN
23,電子遊戲機6-小 計,-,28,-,"1,881,080",-,"124,649",-,"1,231,350",-,"128,299",-,"1,233,462",NaN,NaN,NaN,NaN,NaN
24,電子遊戲機6-電動玩具、小鋼珠A,-,13,-,"1,699,580",-,"115,649",-,"1,141,350",-,"119,749",-,"1,144,870",NaN,NaN,NaN,NaN,NaN
25,電子遊戲機6-娃娃機B,-,-,-,-,-,-,-,-,-,-,-,-,NaN,NaN,NaN,NaN,NaN
26,電子遊戲機6-其 他C,-,15,-,"181,500",-,"9,000",-,"90,000",-,"8,550",-,"88,592",NaN,NaN,NaN,NaN,NaN
27,有節目餐飲業7,-,1,-,"13,125",-,625,-,"8,925",-,625,-,"27,543",NaN,NaN,NaN,NaN,NaN
28,視聽視唱業8-小 計,5,106,"3,196,198","4,267,000","159,631","223,363","1,540,881","2,215,031","159,631","161,620","1,540,881","2,150,623",NaN,NaN,NaN,NaN,NaN
29,視聽視唱業8-KTV(卡拉ok)投幣式A,-,56,-,"1,090,100",-,"59,043",-,"534,335",-,"48,043",-,"577,775",NaN,NaN,NaN,NaN,NaN
30,視聽視唱業8-KTV(卡拉ok)非投幣式B,5,50,"3,196,198","3,176,900","159,631","164,320","1,540,881","1,680,696","159,631","113,275","1,540,881","1,572,546",NaN,NaN,NaN,NaN,NaN
31,視聽視唱業8-MTV C,-,-,-,-,-,-,-,-,-,302,-,302,NaN,NaN,NaN,NaN,NaN
32,視聽視唱業8-其 他D,-,-,-,-,-,-,-,-,-,-,-,-,NaN,NaN,NaN,NaN,NaN
33,其他9-小計,27,283,"19,641,774","11,009,400","494,662","549,275","4,528,479","5,640,250","452,325","526,603","4,483,498","5,655,953",NaN,NaN,NaN,NaN,NaN
34,其他9-資訊休閒業A,-,5,-,"1,224,600",-,"61,230",-,"626,900",-,"56,630",-,"629,262",NaN,NaN,NaN,NaN,NaN
35,其他9-電動搖搖馬B,-,27,-,"155,250",-,"9,000",-,"84,595",-,"9,600",-,"86,670",NaN,NaN,NaN,NaN,NaN
36,其他9-具娛樂性之選物販賣機C,1,170,"46,547","8,234,450","2,116","417,665","30,857","4,362,805","2,116","387,243","30,857","4,405,840",NaN,NaN,NaN,NaN,NaN
37,其他9-機動遊藝樂園D,1,-,"11,655,780",-,"125,265",-,"1,527,913",-,"125,265",-,"1,527,913",-,NaN,NaN,NaN,NaN,NaN
38,其他9-機動遊艇、動力飛行器E,-,17,-,"224,000",-,"7,400",-,"74,000",-,"7,400",-,"73,700",NaN,NaN,NaN,NaN,NaN
39,其他9-實境體感娛樂設施F,1,-,"277,570",-,"13,879",-,"139,759",-,"13,741",-,"139,621",-,NaN,NaN,NaN,NaN,NaN
40,其他9-其他G,24,64,"7,661,877","1,171,100","353,402","53,980","2,829,950","491,950","311,203","65,730","2,785,107","460,481",NaN,NaN,NaN,NaN,NaN
41,臨時公演-小 計,4,NaN,"396,450",-,"1,970",-,"140,530",-,"1,935",-,"142,123",NaN,NaN,NaN,NaN,NaN,NaN
42,臨時公演-職業性歌唱、舞蹈、馬戲、魔術、技藝表演及夜總會之各種表演A,-,-,-,-,-,-,"135,772",-,-,-,"135,772",NaN,NaN,NaN,NaN,NaN,NaN
43,臨時公演-說書、戲劇、音樂演奏及非職業性歌唱、舞蹈等表演B,4,-,"396,450",-,"1,970",-,"4,758",-,"1,935",-,"6,351",NaN,NaN,NaN,NaN,NaN,NaN
44,臨時公演-各種競技比賽C,-,-,-,-,-,-,-,-,-,-,-,NaN,NaN,NaN,NaN,NaN,NaN
45,臨時公演-其他D,-,-,-,-,-,-,-,-,-,-,-,NaN,NaN,NaN,NaN,NaN,NaN
46,違章補徵稅款1,-,-,-,-,-,-,-,-,-,-,-,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
temp = df[['娛樂稅稅源','申報家(件)數','申報營業總額']]
temp

                                 娛樂稅稅源 申報家(件)數        申報營業總額
0                                 合　　計     457    46,702,458
1                              自動申報-總計      35    29,135,403
2                              查定課徵-總計     418    17,170,605
3                              臨時公演-總計       4       396,450
4                            違章補徵稅款-總計     NaN           NaN
5                            電影0-小　　　計      2     2,451,841
6                         電影0-本國片繁榮地區A      -             -
7                         電影0-本國片偏僻地區B      -             -
8                           電影0-本國片郊區C      -             -
9                         電影0-外國片繁榮地區D      -             -
10                        電影0-外國片偏僻地區E      -             -
11                          電影0-外國片郊區F      -             -
12                          電影0-國洋片混片G      2     2,451,841
13                             電影0-其他H      -             -
14                                 歌廳1      -             -
15                               撞球場2　      -             -
16                               保齡球館3      -             -
17                          高爾夫球場4-小　計      1     3,845,590
18                         高爾夫球場4-球　場A      1     3,845,590
19                         高爾夫球場4-練習場B      -             -
20                       舞?舞場    5-小　計      -             -
21                      舞?舞場    5-舞　廳A      -             -
22                      舞?舞場    5-舞　場B      -             -
23                        電子遊戲機6-小　　　計      -             -
24                    電子遊戲機6-電動玩具、小鋼珠A      -             -
25                         電子遊戲機6-娃娃機B      -             -
26                         電子遊戲機6-其　他C      -             -
27                             有節目餐飲業7      -             -
28                        視聽視唱業8-小　　　計      5     3,196,198
29                視聽視唱業8-KTV(卡拉ok)投幣式A      -             -
30               視聽視唱業8-KTV(卡拉ok)非投幣式B      5     3,196,198
31                        視聽視唱業8-MTV C      -             -
32                         視聽視唱業8-其　他D      -             -
33                              其他9-小計     27    19,641,774
34                          其他9-資訊休閒業A      -             -
35                          其他9-電動搖搖馬B      -             -
36                     其他9-具娛樂性之選物販賣機C      1        46,547
37                         其他9-機動遊藝樂園D      1    11,655,780
38                     其他9-機動遊艇、動力飛行器E      -             -
39                       其他9-實境體感娛樂設施F      1       277,570
40                             其他9-其他G     24     7,661,877
41                          臨時公演-小　　　計      4       396,450
42  臨時公演-職業性歌唱、舞蹈、馬戲、魔術、技藝表演及夜總會之各種表演A      -             -
43       臨時公演-說書、戲劇、音樂演奏及非職業性歌唱、舞蹈等表演B      4       396,450
44                        臨時公演-各種競技比賽C      -             -
45                            臨時公演-其他D      -             -
46                             違章補徵稅款1      -             -

In [10]:
Type = temp.groupby(['申報家(件)數'])['娛樂稅稅源','申報營業總額'].sum().reset_index()

C:\Users\Eric\AppData\Local\Temp\ipykernel_21264\2593871068.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  Type = temp.groupby(['申報家(件)數'])['娛樂稅稅源','申報營業總額'].sum().reset_index()

In [12]:
Type = temp.groupby(['申報家(件)數'])['娛樂稅稅源','申報營業總額']
Type

C:\Users\Eric\AppData\Local\Temp\ipykernel_21264\3383526474.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  Type = temp.groupby(['申報家(件)數'])['娛樂稅稅源','申報營業總額']

In [4]:
Type['month'] = ('11月')
Type

,申報家(件)數,娛樂稅稅源,申報營業總額,month
0,-,電影0-本國片繁榮地區A電影0-本國片偏僻地區B電影0-本國片郊區C電影0-外國片繁榮地區D...,- - - - - - - - - - - - - - - ...,11月
1,1,高爾夫球場4-小 計高爾夫球場4-球 場A其他9-具娛樂性之選物販賣機C其他9-機動遊藝樂園...,"3,845,590 3,845,590 46,547 11,655,780 277...",11月
2,2,電影0-小 計電影0-國洋片混片G,"2,451,841 2,451,841",11月
3,24,其他9-其他G,"7,661,877",11月
4,27,其他9-小計,"19,641,774",11月
5,4,臨時公演-小 計臨時公演-說書、戲劇、音樂演奏及非職業性歌唱、舞蹈等表演B,"396,450 396,450",11月
6,5,視聽視唱業8-小 計視聽視唱業8-KTV(卡拉ok)非投幣式B,"3,196,198 3,196,198",11月
7,35,自動申報-總計,"29,135,403",11月
8,4,臨時公演-總計,"396,450",11月
9,418,查定課徵-總計,"17,170,605",11月
10,457,合 計,"46,702,458",11月

In [5]:
import pandas as pd

df1 = pd.read_csv('333.csv')

df1.head()

,娛樂稅稅源,申報家(件)數,查定家(件)數,申報營業總額,查定營業總額,本月份申報報繳稅額,本月份查定報繳稅額,申報報繳稅額累計數,查定報繳稅額累計數,本月份申報實徵稅額,本月份查定實徵稅額,申報實徵稅額累計數,查定實徵稅額累計數,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,合 計,464,NaN,"54,840,164",NaN,"1,760,385",NaN,"19,077,550",NaN,"1,880,420",NaN,"19,126,188",NaN,NaN,NaN,NaN,NaN,NaN
1,自動申報-總計,37,NaN,"31,591,567",NaN,"861,545",NaN,"8,942,624",NaN,"854,355",NaN,"8,890,419",NaN,NaN,NaN,NaN,NaN,NaN
2,查定課徵-總計,419,NaN,"17,033,005",NaN,"891,732",NaN,"9,987,288",NaN,"1,024,485",NaN,"10,092,066",NaN,NaN,NaN,NaN,NaN,NaN
3,臨時公演-總計,8,NaN,"6,215,592",NaN,"7,108",NaN,"147,638",NaN,"1,580",NaN,"143,703",NaN,NaN,NaN,NaN,NaN,NaN
4,違章補徵稅款-總計,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
temp1 = df1[['娛樂稅稅源','申報家(件)數','申報營業總額']]
temp1

                                 娛樂稅稅源 申報家(件)數        申報營業總額
0                                 合　　計     464    54,840,164
1                              自動申報-總計      37    31,591,567
2                              查定課徵-總計     419    17,033,005
3                              臨時公演-總計       8     6,215,592
4                            違章補徵稅款-總計     NaN           NaN
5                            電影0-小　　　計      2     2,079,751
6                         電影0-本國片繁榮地區A      -             -
7                         電影0-本國片偏僻地區B      -             -
8                           電影0-本國片郊區C      -             -
9                         電影0-外國片繁榮地區D      -             -
10                        電影0-外國片偏僻地區E      -             -
11                          電影0-外國片郊區F      -             -
12                          電影0-國洋片混片G      2     2,079,751
13                             電影0-其他H      -             -
14                                 歌廳1      -             -
15                               撞球場2　      -             -
16                               保齡球館3      -             -
17                          高爾夫球場4-小　計      1     4,328,595
18                         高爾夫球場4-球　場A      1     4,328,595
19                         高爾夫球場4-練習場B      -             -
20                       舞?舞場    5-小　計      -             -
21                      舞?舞場    5-舞　廳A      -             -
22                      舞?舞場    5-舞　場B      -             -
23                        電子遊戲機6-小　　　計      -             -
24                    電子遊戲機6-電動玩具、小鋼珠A      -             -
25                         電子遊戲機6-娃娃機B      -             -
26                         電子遊戲機6-其　他C      -             -
27                             有節目餐飲業7      -             -
28                        視聽視唱業8-小　　　計      5     3,330,256
29                視聽視唱業8-KTV(卡拉ok)投幣式A      -             -
30               視聽視唱業8-KTV(卡拉ok)非投幣式B      5     3,330,256
31                        視聽視唱業8-MTV C      -             -
32                         視聽視唱業8-其　他D      -             -
33                              其他9-小計     29    21,852,965
34                          其他9-資訊休閒業A      -             -
35                          其他9-電動搖搖馬B      -             -
36                     其他9-具娛樂性之選物販賣機C      1        74,120
37                         其他9-機動遊藝樂園D      1    14,633,120
38                     其他9-機動遊艇、動力飛行器E      -             -
39                       其他9-實境體感娛樂設施F      1       329,149
40                             其他9-其他G     26     6,816,576
41                          臨時公演-小　　　計      8     6,215,592
42  臨時公演-職業性歌唱、舞蹈、馬戲、魔術、技藝表演及夜總會之各種表演A      -             -
43       臨時公演-說書、戲劇、音樂演奏及非職業性歌唱、舞蹈等表演B      5     1,490,732
44                        臨時公演-各種競技比賽C      3     4,724,860
45                            臨時公演-其他D      -             -
46                             違章補徵稅款1      -             -

In [7]:
type1 = temp1.groupby(['申報家(件)數'])['娛樂稅稅源','申報營業總額'].sum().reset_index()

C:\Users\Eric\AppData\Local\Temp\ipykernel_7280\1917186339.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  type1 = temp1.groupby(['申報家(件)數'])['娛樂稅稅源','申報營業總額'].sum().reset_index()

In [8]:
type1['month'] = ('10月')
type1

,申報家(件)數,娛樂稅稅源,申報營業總額,month
0,-,電影0-本國片繁榮地區A電影0-本國片偏僻地區B電影0-本國片郊區C電影0-外國片繁榮地區D...,- - - - - - - - - - - - - - - ...,10月
1,1,高爾夫球場4-小 計高爾夫球場4-球 場A其他9-具娛樂性之選物販賣機C其他9-機動遊藝樂園...,"4,328,595 4,328,595 74,120 14,633,120 329...",10月
2,2,電影0-小 計電影0-國洋片混片G,"2,079,751 2,079,751",10月
3,26,其他9-其他G,"6,816,576",10月
4,29,其他9-小計,"21,852,965",10月
5,3,臨時公演-各種競技比賽C,"4,724,860",10月
6,5,視聽視唱業8-小 計視聽視唱業8-KTV(卡拉ok)非投幣式B臨時公演-說書、戲劇、音樂...,"3,330,256 3,330,256 1,490,732",10月
7,8,臨時公演-小 計,"6,215,592",10月
8,37,自動申報-總計,"31,591,567",10月
9,419,查定課徵-總計,"17,033,005",10月
10,464,合 計,"54,840,164",10月
11,8,臨時公演-總計,"6,215,592",10月

In [10]:
frames = [ Type , type1]

result = pd.concat(frames)
result

,申報家(件)數,娛樂稅稅源,申報營業總額,month
0,-,電影0-本國片繁榮地區A電影0-本國片偏僻地區B電影0-本國片郊區C電影0-外國片繁榮地區D...,- - - - - - - - - - - - - - - ...,11月
1,1,高爾夫球場4-小 計高爾夫球場4-球 場A其他9-具娛樂性之選物販賣機C其他9-機動遊藝樂園...,"3,845,590 3,845,590 46,547 11,655,780 277...",11月
2,2,電影0-小 計電影0-國洋片混片G,"2,451,841 2,451,841",11月
3,24,其他9-其他G,"7,661,877",11月
4,27,其他9-小計,"19,641,774",11月
5,4,臨時公演-小 計臨時公演-說書、戲劇、音樂演奏及非職業性歌唱、舞蹈等表演B,"396,450 396,450",11月
6,5,視聽視唱業8-小 計視聽視唱業8-KTV(卡拉ok)非投幣式B,"3,196,198 3,196,198",11月
7,35,自動申報-總計,"29,135,403",11月
8,4,臨時公演-總計,"396,450",11月
9,418,查定課徵-總計,"17,170,605",11月
10,457,合 計,"46,702,458",11月
0,-,電影0-本國片繁榮地區A電影0-本國片偏僻地區B電影0-本國片郊區C電影0-外國片繁榮地區D...,- - - - - - - - - - - - - - - ...,10月
1,1,高爾夫球場4-小 計高爾夫球場4-球 場A其他9-具娛樂性之選物販賣機C其他9-機動遊藝樂園...,"4,328,595 4,328,595 74,120 14,633,120 329...",10月
2,2,電影0-小 計電影0-國洋片混片G,"2,079,751 2,079,751",10月
3,26,其他9-其他G,"6,816,576",10月
4,29,其他9-小計,"21,852,965",10月
5,3,臨時公演-各種競技比賽C,"4,724,860",10月
6,5,視聽視唱業8-小 計視聽視唱業8-KTV(卡拉ok)非投幣式B臨時公演-說書、戲劇、音樂...,"3,330,256 3,330,256 1,490,732",10月
7,8,臨時公演-小 計,"6,215,592",10月
8,37,自動申報-總計,"31,591,567",10月
9,419,查定課徵-總計,"17,033,005",10月
10,464,合 計,"54,840,164",10月
11,8,臨時公演-總計,"6,215,592",10月